#
# Sets Oh My Zsh options.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Set the path to Oh My Zsh.
export OMZ="$HOME/.oh-my-zsh"

# Set the key mapping style to 'emacs' or 'vi'.
zstyle ':omz:module:editor' keymap 'emacs'

# Auto convert .... to ../..
zstyle ':omz:module:editor' dot-expansion 'no'

# Set case-sensitivity for completion, history lookup, etc.
zstyle ':omz:*:*' case-sensitive 'yes'

# Color output (auto set to 'no' on dumb terminals).
zstyle ':omz:*:*' color 'yes'

# Auto set the tab and window titles.
zstyle ':omz:module:terminal:auto' title 'yes'

#Set the Zsh modules to load (man zshmodules).
#zstyle ':omz:load' module 'attr' 'stat'

# Set the Zsh functions to load (man zshcontrib).
#zstyle ':omz:load' function 'zargs' 'zmv'

# Set the Oh My Zsh modules to load (browse modules
zstyle ':omz:load' omodule 'environment' 'terminal' 'editor' 'completion' \
                           'history' 'directory' 'spectrum' 'alias' 'utility' 'prompt' \
                           'git' 'ssh-agent' 'tmux'

# Set the prompt theme to load.
# Setting it to 'random' loads a random theme.
# Auto set to 'off' on dumb terminals.
zstyle ':omz:module:prompt' theme 'thegroff'

# This will make you shout: OH MY ZSHELL!
source "$OMZ/init.zsh"

# Customize to your needs...

for d in /usr/local/mysql/bin $HOME/bin
do
  [[ -d "$d" ]] && export PATH="$d:$PATH"
done

unsetopt SHARE_HISTORY
unsetopt AUTO_NAME_DIRS      # Auto add variable-stored paths to ~ list.
unsetopt COMPLETE_IN_WORD    # Complete from both ends of a word
unsetopt CLOBBER             # Don't overwrite existing files with > and >>
unsetopt PATH_DIRS           # Perform path search even on command names with slashes.
unsetopt FLOW_CONTROL        # Allow C-s and C-q to stop/start the terminal flow

[[ -f ~/.rvm/scripts/rvm ]] && source ~/.rvm/scripts/rvm

[[ -f ~/.ansible/set_env ]] && source ~/.ansible/set_env
