if [ "$BASH_PROFILE_LOADED" == "" ]; then
  export BASH_PROFILE_LOADED=$$
  [ -f "$HOME/.profile" ] && source $HOME/.profile
fi

if [[ $- != *i* ]] ; then
  # Shell is non-interactive.  Be done now!
  return
fi

MASH_HOME=$HOME/.mash

#Load environment
source ${MASH_HOME}/environ
#Load alias
source ${MASH_HOME}/alias
#Load colors
source ${MASH_HOME}/colors
#Load prompt
source ${MASH_HOME}/prompt

unset MASH_HOME


[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
