if [ "$BASH_PROFILE_LOADED" == "" ]; then
  export BASH_PROFILE_LOADED=$$
  [ -f "$HOME/.profile" ] && source $HOME/.profile
fi

if [[ $- != *i* ]] ; then
  # Shell is non-interactive.  Be done now!
  return
fi

MASH_HOME=$HOME/.mash

#Load environment
source ${MASH_HOME}/environ
#Load alias
source ${MASH_HOME}/alias
#Load colors
source ${MASH_HOME}/colors

#Load prompt
source ${MASH_HOME}/prompt


#Completion
for comp in ${MASH_HOME}/completion/*
do
  source $comp
done

#Local
[[ -f $HOME/.bash.local ]] && source $HOME/.bash.local

unset MASH_HOME

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

. "$HOME/.cargo/env"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

